### ISSUE TITLE
cool! see also aframe-svgfile-component

### ISSUE THREAD

**Issue by morandd** [mattrei/aframe-geojson-component#1]
Cool component!

There's another SVG renderer:
https://github.com/7dir/aframe-svgfile-component

it uses THREE.MeshLine plugin to handle lines with width other than 1pt. 

anyway, just wanted to mention this

**Comment by mattrei** [comment]
cheers. it needs some polishing. had not the time the last months. 
hope i can finish a usable and documented "release" within this week.

a normal three.line can also draw lines bigger than 1pt... or does this error still exist on windows boxes? MeshLines are more beautiful, true...

**Comment by mattrei** [comment]
also the library uses a different approach, with which i experimented as well. the use svg-mesh-3d library is quite slow.
this d3 approach used here is much faster.
